import re
with open('student.js', 'r') as f:
    content = f.read()

old_text = "Please ensure your Name, Roll Number, and Year are filled out in your profile."
new_text = "Your library card has not been generated by the Librarian yet."

content = content.replace(old_text, new_text)

with open('student.js', 'w') as f:
    f.write(content)
