import re
with open('student.js', 'r') as f:
    content = f.read()

# Remove the "Update Profile" button from the library card unavailable modal
old_html = """                        <p class="text-gray-600 dark:text-gray-300 mb-4">Your library card has not been generated by the Librarian yet.</p>
                        <button onclick="document.getElementById('libraryCardModal').classList.add('hidden'); document.getElementById('editProfileModal').classList.remove('hidden');" class="bg-primary text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-700 transition shadow">Update Profile</button>"""

new_html = """                        <p class="text-gray-600 dark:text-gray-300 mb-4">Your library card has not been generated by the Librarian yet. Please wait for it to be issued.</p>"""

content = content.replace(old_html, new_html)

# Also update the revoked message:
old_revoked = """                        <p class="text-red-500 font-medium mb-4">Your library card was revoked by the librarian. Please update your profile to generate a new one.</p>
                        <button onclick="document.getElementById('libraryCardModal').classList.add('hidden'); document.getElementById('editProfileModal').classList.remove('hidden');" class="bg-primary text-white font-bold py-2 px-4 rounded-lg hover:bg-blue-700 transition">Update Profile</button>"""

new_revoked = """                        <p class="text-red-500 font-medium mb-4">Your library card was permanently deleted by the librarian.</p>"""

content = content.replace(old_revoked, new_revoked)

with open('student.js', 'w') as f:
    f.write(content)
